version 2

seeds : 
  -name : employees
  description : manual map of employees to cutomer
  columns :
      -name : employees_id
      tests :
          -unique
          -not_null
          
