version : 2

seeds : 
  - name : employees
    description : manual map of employees to cutomer
    columns :
      - name : employee_id
        tests:
          - unique
          - not_null
          
        
          
